import { Producto } from "@/types";

export const productos: Producto[] = [
  {
    id: "1",
    nombre: "Ortopédico Cassata",
    slug: "ortopedico-cassata",
    categoria: "colchon",
    descripcion:
      "Opción ideal para soporte extra firme, clínico o de alta resistencia para corregir la postura o aliviar dolores de espalda severos.",
    materiales:
      "18 cm de cassata densidad 100 o 115, tela acolchada género 2 cm",
    firmeza: 5,
    badge: null,
    activo: true,
    orden: 1,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m1",
        producto_id: "1",
        medida: "Individual",
        dimensiones: "1.0m × 1.90m, 20cm alto",
        precio_normal: 590000,
        precio_rebajado: 530000,
        disponible: true,
      },
      {
        id: "m2",
        producto_id: "1",
        medida: "Semidoble",
        dimensiones: "1.20m × 1.90m, 20cm alto",
        precio_normal: 750000,
        precio_rebajado: 650000,
        disponible: true,
      },
      {
        id: "m3",
        producto_id: "1",
        medida: "Doble",
        dimensiones: "1.40m × 1.90m, 20cm alto",
        precio_normal: 790000,
        precio_rebajado: 690000,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i1",
        producto_id: "1",
        url: "/images/colchones/OrtopedicoExtFront.png",
        tipo: "frontal",
        orden: 0,
        alt: "Colchón Ortopédico Cassata - Vista frontal",
      },
      {
        id: "i2",
        producto_id: "1",
        url: "/images/colchones/OrtopedicoExtLado.png",
        tipo: "lateral",
        orden: 1,
        alt: "Colchón Ortopédico Cassata - Vista lateral",
      },
      {
        id: "i3",
        producto_id: "1",
        url: "/images/colchones/Estructura_Ortopedico.png",
        tipo: "estructura",
        orden: 2,
        alt: "Colchón Ortopédico Cassata - Diagrama de capas",
      },
    ],
  },
  {
    id: "2",
    nombre: "Resortado",
    slug: "resortado",
    categoria: "colchon",
    descripcion:
      "Equilibrio perfecto entre soporte ortopédico y confort adaptable.",
    materiales:
      "Unidad resortada ortopédica, aislante de fieltro laminado blanco 7mm, espuma poliflex 3cm, tela género acolchada 1cm",
    firmeza: 4,
    badge: null,
    activo: true,
    orden: 2,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m4",
        producto_id: "2",
        medida: "Individual",
        dimensiones: "1.0m × 1.90m, 26cm alto",
        precio_normal: 590000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m5",
        producto_id: "2",
        medida: "Semidoble",
        dimensiones: "1.20m × 1.90m, 26cm alto",
        precio_normal: 650000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m6",
        producto_id: "2",
        medida: "Doble",
        dimensiones: "1.40m × 1.90m, 26cm alto",
        precio_normal: 690000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i4",
        producto_id: "2",
        url: "/images/colchones/ResortadoExtFront.png",
        tipo: "frontal",
        orden: 0,
        alt: "Colchón Resortado - Vista frontal",
      },
      {
        id: "i5",
        producto_id: "2",
        url: "/images/colchones/ResortadoExtLado.png",
        tipo: "lateral",
        orden: 1,
        alt: "Colchón Resortado - Vista lateral",
      },
      {
        id: "i6",
        producto_id: "2",
        url: "/images/colchones/ResortadoInt.jpeg",
        tipo: "estructura",
        orden: 2,
        alt: "Colchón Resortado - Estructura interna",
      },
    ],
  },
  {
    id: "3",
    nombre: "Super Pillow",
    slug: "super-pillow",
    categoria: "colchon",
    descripcion:
      "Muy cómodo, ideal para personas que quieren algo más suave sin perder firmeza.",
    materiales:
      "Cassata 18cm densidad 115, láminas de espuma penta original 4cm, espuma yakar",
    firmeza: 3,
    badge: "premium",
    activo: true,
    orden: 3,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m7",
        producto_id: "3",
        medida: "Semidoble",
        dimensiones: "1.20m × 1.90m, 32cm alto",
        precio_normal: 1100000,
        precio_rebajado: 900000,
        disponible: true,
      },
      {
        id: "m8",
        producto_id: "3",
        medida: "Doble",
        dimensiones: "1.40m × 1.90m, 32cm alto",
        precio_normal: 1050000,
        precio_rebajado: 950000,
        disponible: true,
      },
      {
        id: "m9",
        producto_id: "3",
        medida: "Queen",
        dimensiones: "1.60m × 1.90m, 32cm alto",
        precio_normal: 1650000,
        precio_rebajado: 1480000,
        disponible: true,
      },
      {
        id: "m10",
        producto_id: "3",
        medida: "King",
        dimensiones: "2.00m × 2.00m, 32cm alto",
        precio_normal: 1950000,
        precio_rebajado: 1650000,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i7",
        producto_id: "3",
        url: "/images/colchones/PillowTop.png",
        tipo: "frontal",
        orden: 0,
        alt: "Colchón Super Pillow Top - Vista frontal",
      },
      {
        id: "i7a",
        producto_id: "3",
        url: "/images/colchones/PillowTopDiagonal.png",
        tipo: "lateral",
        orden: 1,
        alt: "Colchón Super Pillow Top - Vista diagonal",
      },
      {
        id: "i8",
        producto_id: "3",
        url: "/images/colchones/CapasResortadoPillow.png",
        tipo: "estructura",
        orden: 2,
        alt: "Colchón Super Pillow - Diagrama de capas",
      },
    ],
  },
  {
    id: "4",
    nombre: "Resortado Pillow",
    slug: "resortado-pillow",
    categoria: "colchon",
    descripcion:
      "Para personas que quieren algo más suave y alto, con la comodidad del pillow top y el soporte de los resortes.",
    materiales:
      "Tela semi yakar acolchada 2cm, espuma penta 4cm, unidad resortada ortopédica, aislante de fieltro laminado blanco 7mm",
    firmeza: 2,
    badge: null,
    activo: true,
    orden: 4,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m12",
        producto_id: "4",
        medida: "Semidoble",
        dimensiones: "1.20m × 1.90m, 28cm alto",
        precio_normal: 900000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m13",
        producto_id: "4",
        medida: "Doble",
        dimensiones: "1.40m × 1.90m, 28cm alto",
        precio_normal: 950000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m27",
        producto_id: "4",
        medida: "Queen",
        dimensiones: "1.60m × 1.90m, 28cm alto",
        precio_normal: 1480000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i9",
        producto_id: "4",
        url: "/images/colchones/ResortadoPillowFront.png",
        tipo: "frontal",
        orden: 0,
        alt: "Colchón Resortado Pillow - Vista frontal",
      },
      {
        id: "i10",
        producto_id: "4",
        url: "/images/colchones/ResortadoPillow.png",
        tipo: "lateral",
        orden: 1,
        alt: "Colchón Resortado Pillow - Vista lateral",
      },
      {
        id: "i11",
        producto_id: "4",
        url: "/images/colchones/CapasResortadoPillow.png",
        tipo: "estructura",
        orden: 2,
        alt: "Colchón Resortado Pillow - Diagrama de capas",
      },
      {
        id: "i12",
        producto_id: "4",
        url: "/images/colchones/ResortadoPillowInt.jpeg",
        tipo: "ambiente",
        orden: 3,
        alt: "Colchón Resortado Pillow - Estructura interna taller",
      },
    ],
  },
  {
    id: "11",
    nombre: "Resortado Penta",
    slug: "resortado-penta",
    categoria: "colchon",
    descripcion:
      "Comodidad y soporte con espuma penta original para un descanso superior.",
    materiales:
      "Espuma penta original, unidad resortada ortopédica, aislante de fieltro laminado blanco 7mm, tela género acolchada",
    firmeza: 3,
    badge: null,
    activo: true,
    orden: 5,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m28",
        producto_id: "11",
        medida: "Individual",
        dimensiones: "1.0m × 1.90m, 28cm alto",
        precio_normal: 950000,
        precio_rebajado: 850000,
        disponible: true,
      },
      {
        id: "m29",
        producto_id: "11",
        medida: "Semidoble",
        dimensiones: "1.20m × 1.90m, 28cm alto",
        precio_normal: 970000,
        precio_rebajado: 870000,
        disponible: true,
      },
      {
        id: "m30",
        producto_id: "11",
        medida: "Doble",
        dimensiones: "1.40m × 1.90m, 28cm alto",
        precio_normal: 990000,
        precio_rebajado: 890000,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i21",
        producto_id: "11",
        url: "/images/colchones/ResortadoExtFront.png",
        tipo: "frontal",
        orden: 0,
        alt: "Colchón Resortado Penta - Vista frontal",
      },
      {
        id: "i22",
        producto_id: "11",
        url: "/images/colchones/ResortadoExtLado.png",
        tipo: "lateral",
        orden: 1,
        alt: "Colchón Resortado Penta - Vista lateral",
      },
    ],
  },
  {
    id: "5",
    nombre: "Base de cama",
    slug: "base-cama",
    categoria: "base",
    descripcion:
      "Bases divididas en dos módulos fabricadas en madera de pino. Colores: gris, gris oscuro y negro.",
    materiales: "Madera de pino",
    firmeza: null,
    badge: null,
    activo: true,
    orden: 5,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m14",
        producto_id: "5",
        medida: "Individual",
        dimensiones: "1.0m × 1.90m",
        precio_normal: 250000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m15",
        producto_id: "5",
        medida: "Sencillo",
        dimensiones: "1.20m × 1.90m",
        precio_normal: 250000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m16",
        producto_id: "5",
        medida: "Doble",
        dimensiones: "1.40m × 1.90m",
        precio_normal: 250000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m17",
        producto_id: "5",
        medida: "Queen",
        dimensiones: "1.60m × 1.90m",
        precio_normal: 350000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m18",
        producto_id: "5",
        medida: "King",
        dimensiones: "2.00m × 2.00m",
        precio_normal: 420000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "ib1",
        producto_id: "4",
        url: "/images/bases/BaseCamaGris.png",
        tipo: "frontal",
        orden: 0,
        alt: "Base Cama Gris",
      },
      {
        id: "ib2",
        producto_id: "4",
        url: "/images/bases/BaseCamaNegra1.png",
        tipo: "lateral",
        orden: 1,
        alt: "Base Cama Negra",
      },
      {
        id: "ib3",
        producto_id: "4",
        url: "/images/bases/BaseCamaNegraconGris.png",
        tipo: "combinada",
        orden: 2,
        alt: "Base Cama Negra con Gris",
      },
    ],
  },
  {
    id: "6",
    nombre: "Almohada Sencilla",
    slug: "almohada-sencilla",
    categoria: "almohada",
    descripcion: "Cómoda y económica. Ideal para uso diario.",
    materiales: "Tela sencilla, relleno espuma poliflex",
    firmeza: null,
    badge: null,
    activo: true,
    orden: 6,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m19",
        producto_id: "6",
        medida: "Única",
        dimensiones: "Estándar",
        precio_normal: 20000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i13",
        producto_id: "6",
        url: "/images/almohadas/AlmohadaSencilla.png",
        tipo: "frontal",
        orden: 0,
        alt: "Almohada Sencilla",
      },
      {
        id: "i14",
        producto_id: "6",
        url: "/images/almohadas/AlmohadaSencillaLado.png",
        tipo: "lateral",
        orden: 1,
        alt: "Almohada Sencilla - Vista lateral",
      },
    ],
  },
  {
    id: "7",
    nombre: "Almohada Normal",
    slug: "almohada-normal",
    categoria: "almohada",
    descripcion: "Buen confort para descanso con relleno siliconado.",
    materiales: "Relleno siliconado, doble funda con cremallera, tela sencilla",
    firmeza: null,
    badge: null,
    activo: true,
    orden: 7,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m20",
        producto_id: "7",
        medida: "Única",
        dimensiones: "Estándar",
        precio_normal: 25000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i15",
        producto_id: "7",
        url: "/images/almohadas/AlmohadaNormal.png",
        tipo: "frontal",
        orden: 0,
        alt: "Almohada Normal",
      },
      {
        id: "i16",
        producto_id: "7",
        url: "/images/almohadas/AlmohadaNormal_Lado.png",
        tipo: "lateral",
        orden: 1,
        alt: "Almohada Normal - Vista lateral",
      },
    ],
  },
  {
    id: "8",
    nombre: "Almohada Acolchada",
    slug: "almohada-acolchada",
    categoria: "almohada",
    descripcion:
      "Suave, recupera su forma, propiedades hipoalergénicas.",
    materiales:
      "Funda de algodón, fibra siliconada, tela acolchada",
    firmeza: null,
    badge: null,
    activo: true,
    orden: 8,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m21",
        producto_id: "8",
        medida: "Única",
        dimensiones: "Estándar",
        precio_normal: 30000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i17",
        producto_id: "8",
        url: "/images/almohadas/AlmohadaAcolchada.png",
        tipo: "frontal",
        orden: 0,
        alt: "Almohada Acolchada",
      },
      {
        id: "i18",
        producto_id: "8",
        url: "/images/almohadas/AlmohadaAcolchadaLado.png",
        tipo: "lateral",
        orden: 1,
        alt: "Almohada Acolchada - Vista lateral",
      },
    ],
  },
  {
    id: "9",
    nombre: "Almohada Memory Foam",
    slug: "almohada-memory-foam",
    categoria: "almohada",
    descripcion:
      "Alinea la columna, elimina puntos de presión, se moldea al cuello y regresa a su forma.",
    materiales: "Espuma viscoelástica, cremallera",
    firmeza: null,
    badge: "premium",
    activo: true,
    orden: 9,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m22",
        producto_id: "9",
        medida: "Única",
        dimensiones: "Estándar",
        precio_normal: 120000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i19",
        producto_id: "9",
        url: "/images/almohadas/AlmohadaMemory.png",
        tipo: "frontal",
        orden: 0,
        alt: "Almohada Memory Foam",
      },
      {
        id: "i20",
        producto_id: "9",
        url: "/images/almohadas/AlmohadaMemoryLado.png",
        tipo: "lateral",
        orden: 1,
        alt: "Almohada Memory Foam - Vista lateral con contorno cervical",
      },
    ],
  },
  {
    id: "10",
    nombre: "Protector de colchón",
    slug: "protector-colchon",
    categoria: "protector",
    descripcion:
      "Protege su colchón de líquidos y suciedad exterior.",
    materiales: "Tela acolchada",
    firmeza: null,
    badge: null,
    activo: true,
    orden: 10,
    created_at: new Date().toISOString(),
    medidas: [
      {
        id: "m23",
        producto_id: "10",
        medida: "Individual",
        dimensiones: "1.0m × 1.90m",
        precio_normal: 45000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m24",
        producto_id: "10",
        medida: "Sencillo",
        dimensiones: "1.20m × 1.90m",
        precio_normal: 48000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m25",
        producto_id: "10",
        medida: "Doble",
        dimensiones: "1.40m × 1.90m",
        precio_normal: 50000,
        precio_rebajado: null,
        disponible: true,
      },
      {
        id: "m26",
        producto_id: "10",
        medida: "Queen",
        dimensiones: "1.60m × 1.90m",
        precio_normal: 60000,
        precio_rebajado: null,
        disponible: true,
      },
    ],
    imagenes: [
      {
        id: "i13",
        producto_id: "10",
        url: "/images/protectores/ProtectorBlanco.png",
        tipo: "frontal",
        orden: 0,
        alt: "Protector de colchón color blanco - Colchones Posada",
      },
      {
        id: "i14",
        producto_id: "10",
        url: "/images/protectores/ProtectorGris.png",
        tipo: "ambiente",
        orden: 1,
        alt: "Protector de colchón color gris - Colchones Posada",
      },
    ],
  },
];

export function getProductoBySlug(slug: string): Producto | undefined {
  return productos.find((p) => p.slug === slug);
}

export function getProductosByCategoria(
  categoria: Producto["categoria"]
): Producto[] {
  return productos.filter((p) => p.categoria === categoria && p.activo);
}

export function formatPrecio(precio: number): string {
  return `$${precio.toLocaleString("es-CO")}`;
}
